### ISSUE TITLE
Consider using Backbone.Wreqr / Backbone.Radio for events

### ISSUE THREAD

**Issue by samandmoore** [Betterment/backbone.blazer#1]
consider replacing events that exist now with Backbone.Radio / Backbone.Wreqr request/response style pattern to make them more useful.

**Comment by jamesplease** [comment]
Mmm...I don't think the extra dependency would get ya much, but I'm curious to see what you have in mind!

**Comment by samandmoore** [comment]
not going to do this for now. closing.
