### ISSUE TITLE
Promise.resolve the prepare function

### ISSUE THREAD

**Issue by jamesplease** [Betterment/backbone.blazer#14]
``` diff
- route.prepare(routeData).then(function() {
+ Promise.resolve(route.prepare(routeData)).then(function() {
```

This lets you support sync and async prepare methods.

Depends on #13. Competes with https://github.com/Betterment/backbone.blazer/pull/12#discussion_r25262538

**Comment by samandmoore** [comment]
done in: https://github.com/Betterment/backbone.blazer/commit/db9a6a0fcc7cc3a528648021e1871a15fc290736

will replace with `Promise.resolve` once we do #13
