### ISSUE TITLE
re-work route registration

### ISSUE THREAD

**Issue by samandmoore** [Betterment/backbone.blazer#15]
instead of registering routes like this:

```
routes: {
  'foo': new FooRoute()
}
```

we'd like to register like this:

```
routes: {
  'foo': FooRoute
}
```

so that we can construct a new instance of the route for each navigation to that route. this makes it so that the route handler objects are not singleton-esque since they encourage the process of attaching state to themselves.

another approach would be to re-work the inner pipeline in the router so that the router takes the fulfillment values of the `prepare` promise and pipes them into the execute method. then the routes would be able to exist as singleton-esque instances.

**Comment by samandmoore** [comment]
@dschaub thoughts?

**Comment by dschaub** [comment]
I guess the difference between that style and the existing one is that routes can't be reusable. There would no longer be `RouteWithView` or `RouteWithData`, there would be specific implementations of those, which means a bunch of extra classes we might not need. Unless you had a different idea for reusing them?

**Comment by jmileham** [comment]
I also think that when you're doing inversion of control effectively, you should inject instances of things rather than classes of things so that the router could rely on state that was already put into the instance, or at least support it (could you support both just as a shorthand?)

**Comment by samandmoore** [comment]
decided against this. i think what we should push instead is attaching models etc to the `routeData` object that is passed through the chain. this would be good for keeping the route objects stateless themselves.

**Comment by samandmoore** [comment]
example:

``` js
var Route = Blazer.Route.extend({
  prepare: function(routeData) {
    routeData.model = new Account();
    return routeData.model.fetch();
  },
  execute: function(routeData) {
    App.mainRegion.show(new View({ model: routeData.model }));
  }
});
```
