### ISSUE TITLE
add filter chain to Route configuration

### ISSUE THREAD

**Issue by samandmoore** [Betterment/backbone.blazer#4]
it would be nice to be able to pre-filter routes before they're executed.

example api:

we could allow this to just be a function that returns true to continue and false to bail out early.

``` js
Backbone.Blazer.Route.extend({
  filters: [(routeData) => { // true continues, false bails early }]
});
```

but what do we do if we bail out early? we trigger error? sounds crummy.
## 

another idea:

we could create a special object like `Route`

``` js
Backbone.Blazer.Filter = Marionette.Object.extend({
  test: function(routeData) { // true/false },
  failed: function(routeData) {
    // called if test returns false
    // allows this filter to handle what happens if it fails
    // e.g. an auth filter could have this do a redirect to the log-in view
  }
});

Backbone.Blazer.Route.extend({
  filters: [new AuthenticatedFilter()]
});
```
## 

questions:
- should this support asynchronous filters? (leaning toward no).

**Comment by jamesplease** [comment]
Have you used/looked at [Ember's router](http://emberjs.com/guides/routing/)? I think that the API they expose pretty much completely covers all of the use cases for a client side router. It might save you some bike-shedding if you look over their documentation a few times.

**Comment by samandmoore** [comment]
done in #19
