### ISSUE TITLE
Remove Marionette dependency

### ISSUE THREAD

**Issue by jamesplease** [Betterment/backbone.blazer#6]
There's not really anything Marionette-specific in here. I'd just use a good ol' JavaScript function for your 'Route' object, then mix in the Backbone goodies like `extend` and `Events`.

If, in your own applications, you use Marionette features like `triggerMethod`, you could add them to your application by extending the Route class. The benefit to this change is that it makes the library usable by more of the Backbone community.

This issue competes with https://github.com/samccone/backbone.blazer/commit/7faf9a7e968d7bc1b6e04c36ff359b4250a1fe6f.

**Comment by samandmoore** [comment]
resolved here: https://github.com/Betterment/backbone.blazer/pull/12
